### ISSUE TITLE
Crash with ViaFabricPlus

### ISSUE THREAD

**Issue by HowardZHY** [JustAlittleWolf/ServerPingerFixer#4]
[crash-2023-07-15_01.42.03-client.txt](https://github.com/JustAlittleWolf/ServerPingerFixer/files/12052787/crash-2023-07-15_01.42.03-client.txt)

I think it may reproduce with below 1.6.4 protocol

**Comment by JustAlittleWolf** [comment]
Will take a look at this when I have time

**Comment by JustAlittleWolf** [comment]
does this issue happen only with the specific protocol?

**Comment by HowardZHY** [comment]
I've tried multiple times but I don't think I can reproduce it anymore

**Comment by JustAlittleWolf** [comment]
Hmm was probably an issue with ViaFabricPlus then. I can't find anything related to my mod in your crash log file anywhere. My mod shouldn't really affect other mods as it's just a simple mixin with no practical point of failure. I'll mark this issue as closed now, reopen it if you can get it to work again.
