### ISSUE TITLE
More optimization

### ISSUE THREAD

**Issue by andreasdc** [JustAlittleWolf/ServerPingerFixer#5]
Hey, nice mod, I think it works better than normally, do you think it can be optimized more? Like improving the pinging mechanic, because sometimes it can get stuck for some time or load slowly.

**Comment by JustAlittleWolf** [comment]
Hi, unfortunately this isn't really possible as sometimes servers restrict how often you can ping them to avoid a ddos attack. In case the issue lies with how the client handles network connections an improvement might be possible but I am not knowledgeable enough with barebones networking to do that.

**Comment by andreasdc** [comment]
Would be really nice to have it really fixed, I was stuck on connecting to the server for like 3 minutes and no servers were possible to ping too.

**Comment by JustAlittleWolf** [comment]
That is not an issue with Minecraft, if you cannot connect to any server your internet is most likely down at the moment. The servers can also block you for connection spamming as I've told you.

**Comment by andreasdc** [comment]
By the way when you connect to the server, pinging other server doesn't stop, that's the reason you need to wait for them to finish so you can join. It happens when you have around 10+ server and not so fast pc.

**Comment by andreasdc** [comment]
For example on 1.12.2 pinging is almost instant

**Comment by andreasdc** [comment]
Can you try closing pinging connections when you connect to a server?
