### ISSUE TITLE
Port patch from another mod

### ISSUE THREAD

**Issue by andreasdc** [JustAlittleWolf/ServerPingerFixer#6]
Hey, I found this mod:
https://github.com/Nixuge/ServerlistBufferFixer
Do you think it's possible to port it to your mod?

**Comment by JustAlittleWolf** [comment]
Hello! My mod was inspired by Nixuge's ServerlistBufferFixer, it does exactly the same thing. The implementation is a little different, as Minecrafts code has changed since 1.8.9.

**Comment by andreasdc** [comment]
All right, I found 2 mods, that at the moment greatly improve pinging:
https://modrinth.com/mod/bannedserverbypass
https://modrinth.com/mod/fast-ip-ping

**Comment by JustAlittleWolf** [comment]
Great, you can download and use them! Unfortunately I won't include them in this mod as you can already use them as is and I don't want to steal their functionality.

**Comment by andreasdc** [comment]
I use them, that's what you can understand from my previous message, but after some time it gets slow again.

**Comment by JustAlittleWolf** [comment]
What slows down exactly? Does that happen without my/all mods as well?

**Comment by andreasdc** [comment]
After some time or couple refreshes pings are infinite and you can't join any server, I think it happens in all scenarios.

**Comment by JustAlittleWolf** [comment]
Could this be a bandwidth issue? If your home internet is too slow, the router might stop additional traffic to wait for others to be sent. You can check here: https://speedtest.net

**Comment by andreasdc** [comment]
Definitely not bandwith issue.
